const HEATMAP_UNIVERSE_USA = [
  { ticker: 'MSFT', sector: 'Technology', industry: 'Software - Infrastructure', marketCap: 3100000000000 },
  { ticker: 'ORCL', sector: 'Technology', industry: 'Software - Infrastructure', marketCap: 470000000000 },
  { ticker: 'PLTR', sector: 'Technology', industry: 'Software - Infrastructure', marketCap: 220000000000 },
  { ticker: 'SNPS', sector: 'Technology', industry: 'Software - Application', marketCap: 90000000000 },
  { ticker: 'CRM', sector: 'Technology', industry: 'Software - Application', marketCap: 270000000000 },
  { ticker: 'ADBE', sector: 'Technology', industry: 'Software - Application', marketCap: 240000000000 },
  { ticker: 'INTU', sector: 'Technology', industry: 'Software - Application', marketCap: 180000000000 },
  { ticker: 'NOW', sector: 'Technology', industry: 'Software - Application', marketCap: 160000000000 },
  { ticker: 'IBM', sector: 'Technology', industry: 'Information Technology Services', marketCap: 240000000000 },
  { ticker: 'ACN', sector: 'Technology', industry: 'Information Technology Services', marketCap: 210000000000 },
  { ticker: 'CSCO', sector: 'Technology', industry: 'Communication Equipment', marketCap: 200000000000 },
  { ticker: 'ANET', sector: 'Technology', industry: 'Communication Equipment', marketCap: 120000000000 },
  { ticker: 'NVDA', sector: 'Technology', industry: 'Semiconductors', marketCap: 4300000000000 },
  { ticker: 'AVGO', sector: 'Technology', industry: 'Semiconductors', marketCap: 1600000000000 },
  { ticker: 'AMD', sector: 'Technology', industry: 'Semiconductors', marketCap: 360000000000 },
  { ticker: 'MU', sector: 'Technology', industry: 'Semiconductors', marketCap: 140000000000 },
  { ticker: 'QCOM', sector: 'Technology', industry: 'Semiconductors', marketCap: 250000000000 },
  { ticker: 'TXN', sector: 'Technology', industry: 'Semiconductors', marketCap: 190000000000 },
  { ticker: 'AMAT', sector: 'Technology', industry: 'Semiconductor Equipment & Materials', marketCap: 170000000000 },
  { ticker: 'LRCX', sector: 'Technology', industry: 'Semiconductor Equipment & Materials', marketCap: 120000000000 },
  { ticker: 'KLAC', sector: 'Technology', industry: 'Semiconductor Equipment & Materials', marketCap: 100000000000 },
  { ticker: 'INTC', sector: 'Technology', industry: 'Semiconductors', marketCap: 130000000000 },
  { ticker: 'AAPL', sector: 'Technology', industry: 'Consumer Electronics', marketCap: 3800000000000 },
  { ticker: 'AMZN', sector: 'Consumer Cyclical', industry: 'Internet Retail', marketCap: 2400000000000 },
  { ticker: 'BKNG', sector: 'Consumer Cyclical', industry: 'Travel Services', marketCap: 160000000000 },
  { ticker: 'UBER', sector: 'Consumer Cyclical', industry: 'Software - Application', marketCap: 170000000000 },
  { ticker: 'TSLA', sector: 'Consumer Cyclical', industry: 'Auto Manufacturers', marketCap: 980000000000 },
  { ticker: 'HD', sector: 'Consumer Cyclical', industry: 'Home Improvement', marketCap: 360000000000 },
  { ticker: 'LOW', sector: 'Consumer Cyclical', industry: 'Home Improvement', marketCap: 140000000000 },
  { ticker: 'MCD', sector: 'Consumer Cyclical', industry: 'Restaurants', marketCap: 220000000000 },
  { ticker: 'CMG', sector: 'Consumer Cyclical', industry: 'Restaurants', marketCap: 80000000000 },
  { ticker: 'TJX', sector: 'Consumer Cyclical', industry: 'Apparel Retail', marketCap: 130000000000 },
  { ticker: 'NKE', sector: 'Consumer Cyclical', industry: 'Apparel Retail', marketCap: 110000000000 },
  { ticker: 'GOOGL', sector: 'Communication Services', industry: 'Internet Content & Information', marketCap: 2300000000000 },
  { ticker: 'META', sector: 'Communication Services', industry: 'Internet Content & Information', marketCap: 1500000000000 },
  { ticker: 'NFLX', sector: 'Communication Services', industry: 'Entertainment', marketCap: 520000000000 },
  { ticker: 'DIS', sector: 'Communication Services', industry: 'Entertainment', marketCap: 180000000000 },
  { ticker: 'CMCSA', sector: 'Communication Services', industry: 'Telecom Services', marketCap: 160000000000 },
  { ticker: 'TMUS', sector: 'Communication Services', industry: 'Telecom Services', marketCap: 330000000000 },
  { ticker: 'VZ', sector: 'Communication Services', industry: 'Telecom Services', marketCap: 190000000000 },
  { ticker: 'T', sector: 'Communication Services', industry: 'Telecom Services', marketCap: 130000000000 },
  { ticker: 'WMT', sector: 'Consumer Defensive', industry: 'Discount Stores', marketCap: 780000000000 },
  { ticker: 'COST', sector: 'Consumer Defensive', industry: 'Discount Stores', marketCap: 420000000000 },
  { ticker: 'KO', sector: 'Consumer Defensive', industry: 'Beverages - Non-Alcoholic', marketCap: 320000000000 },
  { ticker: 'PG', sector: 'Consumer Defensive', industry: 'Household & Personal Products', marketCap: 380000000000 },
  { ticker: 'PEP', sector: 'Consumer Defensive', industry: 'Beverages - Non-Alcoholic', marketCap: 240000000000 },
  { ticker: 'PM', sector: 'Consumer Defensive', industry: 'Tobacco', marketCap: 150000000000 },
  { ticker: 'MO', sector: 'Consumer Defensive', industry: 'Tobacco', marketCap: 90000000000 },
  { ticker: 'CL', sector: 'Consumer Defensive', industry: 'Household & Personal Products', marketCap: 80000000000 },
  { ticker: 'KMB', sector: 'Consumer Defensive', industry: 'Household & Personal Products', marketCap: 45000000000 },
  { ticker: 'LLY', sector: 'Healthcare', industry: 'Drug Manufacturers - General', marketCap: 720000000000 },
  { ticker: 'JNJ', sector: 'Healthcare', industry: 'Drug Manufacturers - General', marketCap: 370000000000 },
  { ticker: 'MRK', sector: 'Healthcare', industry: 'Drug Manufacturers - General', marketCap: 210000000000 },
  { ticker: 'ABBV', sector: 'Healthcare', industry: 'Drug Manufacturers - General', marketCap: 340000000000 },
  { ticker: 'PFE', sector: 'Healthcare', industry: 'Drug Manufacturers - General', marketCap: 160000000000 },
  { ticker: 'UNH', sector: 'Healthcare', industry: 'Healthcare Plans', marketCap: 470000000000 },
  { ticker: 'ABT', sector: 'Healthcare', industry: 'Medical Devices', marketCap: 220000000000 },
  { ticker: 'TMO', sector: 'Healthcare', industry: 'Diagnostics & Research', marketCap: 200000000000 },
  { ticker: 'DHR', sector: 'Healthcare', industry: 'Diagnostics & Research', marketCap: 180000000000 },
  { ticker: 'ISRG', sector: 'Healthcare', industry: 'Medical Devices', marketCap: 160000000000 },
  { ticker: 'JPM', sector: 'Financial', industry: 'Banks - Diversified', marketCap: 670000000000 },
  { ticker: 'BAC', sector: 'Financial', industry: 'Banks - Diversified', marketCap: 320000000000 },
  { ticker: 'WFC', sector: 'Financial', industry: 'Banks - Diversified', marketCap: 260000000000 },
  { ticker: 'C', sector: 'Financial', industry: 'Banks - Diversified', marketCap: 120000000000 },
  { ticker: 'PNC', sector: 'Financial', industry: 'Banks - Regional', marketCap: 70000000000 },
  { ticker: 'V', sector: 'Financial', industry: 'Credit Services', marketCap: 650000000000 },
  { ticker: 'MA', sector: 'Financial', industry: 'Credit Services', marketCap: 520000000000 },
  { ticker: 'AXP', sector: 'Financial', industry: 'Credit Services', marketCap: 160000000000 },
  { ticker: 'BRK-B', sector: 'Financial', industry: 'Insurance - Diversified', marketCap: 1150000000000 },
  { ticker: 'BLK', sector: 'Financial', industry: 'Asset Management', marketCap: 120000000000 },
  { ticker: 'SPGI', sector: 'Financial', industry: 'Financial Data & Stock Exchanges', marketCap: 160000000000 },
  { ticker: 'SCHW', sector: 'Financial', industry: 'Capital Markets', marketCap: 140000000000 },
  { ticker: 'GS', sector: 'Financial', industry: 'Capital Markets', marketCap: 220000000000 },
  { ticker: 'MS', sector: 'Financial', industry: 'Capital Markets', marketCap: 250000000000 },
  { ticker: 'GE', sector: 'Industrials', industry: 'Aerospace & Defense', marketCap: 240000000000 },
  { ticker: 'RTX', sector: 'Industrials', industry: 'Aerospace & Defense', marketCap: 180000000000 },
  { ticker: 'BA', sector: 'Industrials', industry: 'Aerospace & Defense', marketCap: 120000000000 },
  { ticker: 'CAT', sector: 'Industrials', industry: 'Farm & Heavy Construction', marketCap: 180000000000 },
  { ticker: 'DE', sector: 'Industrials', industry: 'Farm & Heavy Construction', marketCap: 140000000000 },
  { ticker: 'LMT', sector: 'Industrials', industry: 'Aerospace & Defense', marketCap: 120000000000 },
  { ticker: 'HON', sector: 'Industrials', industry: 'Conglomerates', marketCap: 140000000000 },
  { ticker: 'UNP', sector: 'Industrials', industry: 'Railroads', marketCap: 140000000000 },
  { ticker: 'UPS', sector: 'Industrials', industry: 'Integrated Freight & Logistics', marketCap: 120000000000 },
  { ticker: 'ETN', sector: 'Industrials', industry: 'Specialty Industrial Machinery', marketCap: 130000000000 },
  { ticker: 'WM', sector: 'Industrials', industry: 'Waste Management', marketCap: 90000000000 },
  { ticker: 'XOM', sector: 'Energy', industry: 'Oil & Gas Integrated', marketCap: 510000000000 },
  { ticker: 'CVX', sector: 'Energy', industry: 'Oil & Gas Integrated', marketCap: 300000000000 },
  { ticker: 'COP', sector: 'Energy', industry: 'Oil & Gas E&P', marketCap: 160000000000 },
  { ticker: 'SLB', sector: 'Energy', industry: 'Oil & Gas Equipment & Services', marketCap: 90000000000 },
  { ticker: 'EOG', sector: 'Energy', industry: 'Oil & Gas E&P', marketCap: 70000000000 },
  { ticker: 'MPC', sector: 'Energy', industry: 'Oil & Gas Refining & Marketing', marketCap: 70000000000 },
  { ticker: 'OXY', sector: 'Energy', industry: 'Oil & Gas E&P', marketCap: 60000000000 },
  { ticker: 'PLD', sector: 'Real Estate', industry: 'REIT - Industrial', marketCap: 110000000000 },
  { ticker: 'AMT', sector: 'Real Estate', industry: 'REIT - Specialty', marketCap: 95000000000 },
  { ticker: 'EQIX', sector: 'Real Estate', industry: 'REIT - Specialty', marketCap: 85000000000 },
  { ticker: 'PSA', sector: 'Real Estate', industry: 'REIT - Industrial', marketCap: 50000000000 },
  { ticker: 'CCI', sector: 'Real Estate', industry: 'REIT - Specialty', marketCap: 45000000000 },
  { ticker: 'NEE', sector: 'Utilities', industry: 'Utilities - Regulated Electric', marketCap: 160000000000 },
  { ticker: 'SO', sector: 'Utilities', industry: 'Utilities - Regulated Electric', marketCap: 95000000000 },
  { ticker: 'DUK', sector: 'Utilities', industry: 'Utilities - Regulated Electric', marketCap: 90000000000 },
  { ticker: 'AEP', sector: 'Utilities', industry: 'Utilities - Regulated Electric', marketCap: 55000000000 },
];

const HEATMAP_UNIVERSE_ARGENTINA_ARS = [
  { symbol: 'AGRO', name: 'Agrometal', sector: 'Industrials', industry: 'Agricultural Machinery' },
  { symbol: 'ALUA', name: 'Aluar', sector: 'Materials', industry: 'Aluminum' },
  { symbol: 'BBAR', name: 'Banco BBVA Argentina', sector: 'Financials', industry: 'Banks' },
  { symbol: 'BHIP', name: 'Banco Hipotecario', sector: 'Financials', industry: 'Banks' },
  { symbol: 'BMA', name: 'Banco Macro', sector: 'Financials', industry: 'Banks' },
  { symbol: 'BPAT', name: 'Banco Patagonia', sector: 'Financials', industry: 'Banks' },
  { symbol: 'BYMA', name: 'BYMA', sector: 'Financials', industry: 'Capital Markets' },
  { symbol: 'CEPU', name: 'Central Puerto', sector: 'Utilities', industry: 'Power Generation' },
  { symbol: 'COME', name: 'Sociedad Comercial del Plata', sector: 'Industrials', industry: 'Conglomerates' },
  { symbol: 'CRES', name: 'Cresud', sector: 'Real Estate', industry: 'Agribusiness & Real Estate' },
  { symbol: 'CVH', name: 'Cablevision Holding', sector: 'Communication Services', industry: 'Telecom & Media' },
  { symbol: 'EDN', name: 'Edenor', sector: 'Utilities', industry: 'Electric Distribution' },
  { symbol: 'GGAL', name: 'Grupo Financiero Galicia', sector: 'Financials', industry: 'Banks' },
  { symbol: 'HAVA', name: 'Havanna', sector: 'Consumer Staples', industry: 'Food Products' },
  { symbol: 'IRSA', name: 'IRSA', sector: 'Real Estate', industry: 'Real Estate' },
  { symbol: 'LOMA', name: 'Loma Negra', sector: 'Materials', industry: 'Construction Materials' },
  { symbol: 'METR', name: 'Metrogas', sector: 'Utilities', industry: 'Gas Distribution' },
  { symbol: 'PAMP', name: 'Pampa Energia', sector: 'Energy', industry: 'Integrated Energy' },
  { symbol: 'SUPV', name: 'Grupo Supervielle', sector: 'Financials', industry: 'Banks' },
  { symbol: 'TECO2', name: 'Telecom Argentina', sector: 'Communication Services', industry: 'Telecom Services' },
  { symbol: 'TGNO4', name: 'Transportadora de Gas del Norte', sector: 'Utilities', industry: 'Gas Transportation' },
  { symbol: 'TGSU2', name: 'Transportadora de Gas del Sur', sector: 'Energy', industry: 'Midstream Gas' },
  { symbol: 'TRAN', name: 'Transener', sector: 'Utilities', industry: 'Electric Transmission' },
  { symbol: 'TXAR', name: 'Ternium Argentina', sector: 'Materials', industry: 'Steel' },
  { symbol: 'VALO', name: 'Banco de Valores', sector: 'Financials', industry: 'Banks' },
  { symbol: 'YPFD', name: 'YPF', sector: 'Energy', industry: 'Integrated Energy' },
];

const HEATMAP_UNIVERSE_ARGENTINA_USD = [
  { symbol: 'ALUAD', historySymbol: 'ALUA', name: 'Aluar (USD)', sector: 'Materials', industry: 'Aluminum' },
  { symbol: 'BBARD', historySymbol: 'BBAR', name: 'Banco BBVA Argentina (USD)', sector: 'Financials', industry: 'Banks' },
  { symbol: 'BMA.D', historySymbol: 'BMA', name: 'Banco Macro (USD)', sector: 'Financials', industry: 'Banks' },
  { symbol: 'BYMAD', historySymbol: 'BYMA', name: 'BYMA (USD)', sector: 'Financials', industry: 'Capital Markets' },
  { symbol: 'CEPUD', historySymbol: 'CEPU', name: 'Central Puerto (USD)', sector: 'Utilities', industry: 'Power Generation' },
  { symbol: 'COMED', historySymbol: 'COME', name: 'Sociedad Comercial del Plata (USD)', sector: 'Industrials', industry: 'Conglomerates' },
  { symbol: 'CRESD', historySymbol: 'CRES', name: 'Cresud (USD)', sector: 'Real Estate', industry: 'Agribusiness & Real Estate' },
  { symbol: 'CVHD', historySymbol: 'CVH', name: 'Cablevision Holding (USD)', sector: 'Communication Services', industry: 'Telecom & Media' },
  { symbol: 'EDND', historySymbol: 'EDN', name: 'Edenor (USD)', sector: 'Utilities', industry: 'Electric Distribution' },
  { symbol: 'GGALD', historySymbol: 'GGAL', name: 'Grupo Financiero Galicia (USD)', sector: 'Financials', industry: 'Banks' },
  { symbol: 'IRSAD', historySymbol: 'IRSA', name: 'IRSA (USD)', sector: 'Real Estate', industry: 'Real Estate' },
  { symbol: 'LOMAD', historySymbol: 'LOMA', name: 'Loma Negra (USD)', sector: 'Materials', industry: 'Construction Materials' },
  { symbol: 'METRD', historySymbol: 'METR', name: 'Metrogas (USD)', sector: 'Utilities', industry: 'Gas Distribution' },
  { symbol: 'PAMPD', historySymbol: 'PAMP', name: 'Pampa Energia (USD)', sector: 'Energy', industry: 'Integrated Energy' },
  { symbol: 'SUPVD', historySymbol: 'SUPV', name: 'Grupo Supervielle (USD)', sector: 'Financials', industry: 'Banks' },
  { symbol: 'TECOD', historySymbol: 'TECO2', name: 'Telecom Argentina (USD)', sector: 'Communication Services', industry: 'Telecom Services' },
  { symbol: 'TGN4D', historySymbol: 'TGNO4', name: 'Transportadora de Gas del Norte (USD)', sector: 'Utilities', industry: 'Gas Transportation' },
  { symbol: 'TGSUD', historySymbol: 'TGSU2', name: 'Transportadora de Gas del Sur (USD)', sector: 'Energy', industry: 'Midstream Gas' },
  { symbol: 'TRAND', historySymbol: 'TRAN', name: 'Transener (USD)', sector: 'Utilities', industry: 'Electric Transmission' },
  { symbol: 'TXARD', historySymbol: 'TXAR', name: 'Ternium Argentina (USD)', sector: 'Materials', industry: 'Steel' },
  { symbol: 'VALOD', historySymbol: 'VALO', name: 'Banco de Valores (USD)', sector: 'Financials', industry: 'Banks' },
  { symbol: 'YPFDD', historySymbol: 'YPFD', name: 'YPF (USD)', sector: 'Energy', industry: 'Integrated Energy' },
];

const HEATMAP_RULES_BY_MARKET = {
  usa: {
    market: 'usa',
    rangeEnabled: true,
    dailyOnly: false,
    sizeMetric: 'market-cap',
  },
  'argentina-ars': {
    market: 'argentina-ars',
    rangeEnabled: true,
    dailyOnly: false,
    sizeMetric: 'price-times-volume',
  },
  'argentina-usd': {
    market: 'argentina-usd',
    rangeEnabled: false,
    dailyOnly: true,
    sizeMetric: 'price-times-volume',
  },
};

const HEATMAP_UNIVERSE_BY_MARKET = {
  usa: HEATMAP_UNIVERSE_USA,
  'argentina-ars': HEATMAP_UNIVERSE_ARGENTINA_ARS,
  'argentina-usd': HEATMAP_UNIVERSE_ARGENTINA_USD,
};

function getHeatmapUniverse(market = 'usa') {
  return HEATMAP_UNIVERSE_BY_MARKET[market] || HEATMAP_UNIVERSE_USA;
}

function getHeatmapRules(market = 'usa') {
  return HEATMAP_RULES_BY_MARKET[market] || HEATMAP_RULES_BY_MARKET.usa;
}

module.exports = {
  HEATMAP_UNIVERSE_USA,
  HEATMAP_UNIVERSE_ARGENTINA_ARS,
  HEATMAP_UNIVERSE_ARGENTINA_USD,
  HEATMAP_UNIVERSE_BY_MARKET,
  HEATMAP_RULES_BY_MARKET,
  getHeatmapUniverse,
  getHeatmapRules,
};
